name: Elixir Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir-version: ['1.18']
        otp-version: ['26']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}
    
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-
    
    - name: Restore build cache
      uses: actions/cache@v3
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Compile
      run: mix compile
    
    - name: Run tests
      run: mix test
    
    - name: Run tests with coverage
      run: mix test --cover
      if: matrix.elixir-version == '1.18'
    
    - name: Run credo (code quality)
      run: mix credo
      if: matrix.elixir-version == '1.18'
    
    - name: Run dialyzer (static analysis)
      run: mix dialyzer
      if: matrix.elixir-version == '1.18'
      continue-on-error: true
